# Generated by Django 3.0 on 2023-12-21 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_dashboard_app', '0002_auto_20231221_1709'),
        ('app_1', '0003_auto_20231221_1709'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_text', models.TextField()),
                ('Notification_time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 17, 9, 50, 923822))),
                ('Notification_stuff', models.ManyToManyField(blank=True, null=True, to='app_1.Staff_Access')),
                ('Notification_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_dashboard_app.vendor_registration_table')),
            ],
            options={
                'verbose_name_plural': 'Vendor Notifications',
            },
        ),
        migrations.CreateModel(
            name='Order_notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_text', models.TextField()),
                ('Notification_time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 17, 9, 50, 923014))),
                ('Notification_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Order_Table')),
                ('Notification_stuff', models.ManyToManyField(blank=True, null=True, to='app_1.Staff_Access')),
            ],
            options={
                'verbose_name_plural': 'Order Notifications',
            },
        ),
    ]
