# Generated by Django 3.0 on 2023-12-23 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_notifications',
            name='Notification_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 23, 23, 8, 43, 61821)),
        ),
        migrations.AlterField(
            model_name='vendor_notifications',
            name='Notification_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 23, 23, 8, 43, 62814)),
        ),
    ]
