# Generated by Django 3.0 on 2023-12-24 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard_app', '0004_auto_20231223_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_registration_table',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 24, 10, 50, 32, 620182)),
        ),
    ]
